# Generated by Django 5.0.1 on 2026-02-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_zoom_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='grade',
            new_name='core_grade_student_516fcf_idx',
            old_name='core_grade_student_checked_idx',
        ),
        migrations.RenameIndex(
            model_name='grade',
            new_name='core_grade_student_77dac7_idx',
            old_name='core_grade_student_status_idx',
        ),
    ]
